name: Formatting check

# CINTENT >> MANUAL TRIGGER
# on:
# - pull_request
on: [repository_dispatch, workflow_dispatch]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      # CINTENT >> NEED_API_KEY
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.4.1
      #   with:
      #     access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install black

      - name: Run Black
        run: black -l 100 strawberryfields/ tests/ --check

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
